### PR TITLE
Resolves #147 Form is submitted when required checkboxes are not checked

### LINKED ISSUE #147: Form is submitted when required checkboxes are not checked
Hi everybody!
I found this bug while I was working with checkboxes, I don't know if the same problem occurs with radio inputs.

Here is a [plunker](http://plnkr.co/edit/YmPyWsskmv0ioGLSpfd9?p=preview) showing the problem, just perform the following steps:
* try to submit
* check the input
* uncheck the input
* try again to submit the form

You will notice than from now on, the form is always submitted even if the input is not checked. As you will see, also `field-error`s are never shown.

### PR DESCRIPTION
**Pull request by indrimuska**
Here is the [plunker](http://plnkr.co/edit/mw2nrMo0w9lTarbb4QmH?p=preview).

### CODE REVIEW

**Comment by bvaughn** [comment]
Hey @indrimuska,

Thanks for sharing this idea. I can't merge it as-is however, since it's only a change to the dist file and not the source. Also if I'm reading it correctly, it would break fields with values like `0` or `false` or `''` (empty string).

Going to need to give this some more thought.

**Comment by indrimuska** [comment]
Hi @bvaughn, you're right, next time I'll make my changes also to source files.

Just one question: I don't understand why you're saying that **it would break fields with values like `0` or `false` or `''`**. Is there any way to set the two values of a single checkbox? I haven't found anything into the documentation site. Maybe I'm missing something.

**Comment by bvaughn** [comment]
My apologies. I was only able to glance at your PR briefly because I was at work. For some reason I thought you had made your change to the `FieldHelper` (which is used by all of the input types). Looking again, this is obviously not the case so you can disregard the second half of my earlier statement. :)

**Comment by indrimuska** [comment]
Ah ok, don't worry, no problem! :smile:

Maybe you misunderstood the [comment](https://github.com/bvaughn/angular-form-for/issues/147#issuecomment-125912780) I made in #147, or maybe it was not so clear as I think (this proposal is about option n.2 - adding a specific watcher to `checkbox-field` directive).

If you like this solution I can update the PR.

**Comment by bvaughn** [comment]
If you've tested it and it seems to work- let's go for it. I'll give it another test myself once you've got a PR with source+dist modifications. :)

**Comment by bvaughn** [comment]
Oh hi. I haven't been intending to ignore this, I just didn't get a notice that you'd updated your branch.

Let me take a look here... :)

**Pull request closed without merging**
